# Copyright 2023 Datum Technology Corporation
# All rights reserved.
########################################################################################################################


[project]
name        = "name"
full-name   = "Project Name"
description = ""
